name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Install cbmc
      run: wget https://github.com/diffblue/cbmc/releases/download/cbmc-6.3.1/ubuntu-22.04-cbmc-6.3.1-Linux.deb && sudo dpkg -i ubuntu-22.04-cbmc-6.3.1-Linux.deb && goto-cc --version
    - uses: actions/checkout@v4
    - name: Install ESBMC
      run: wget https://github.com/esbmc/esbmc/releases/download/nightly-7867f5e5595b9e181cd36eb9155d1905f87ad241/esbmc-linux.zip && unzip esbmc-linux.zip && chmod +x ./linux-release/bin/esbmc && ./linux-release/bin/esbmc --version
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: GOTO_CC=goto-cc ESBMC=$PWD/linux-release/bin/esbmc cargo test -- --ignored
