name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Install cbmc
      run: wget https://github.com/diffblue/cbmc/releases/download/cbmc-6.3.1/ubuntu-22.04-cbmc-6.3.1-Linux.deb && sudo dpkg -i ubuntu-22.04-cbmc-6.3.1-Linux.deb && goto-cc --version
    - uses: actions/checkout@v4
    - name: Install ESBMC
      run: wget https://github.com/esbmc/esbmc/releases/download/v7.6.1/release-ubuntu-latest.zip && unzip release-ubuntu-latest.zip && chmod +x ./bin/esbmc && ./bin/esbmc --version
    - name: Build
      run: cargo build --verbose
