name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    - name: Install cbmc
      run: sudo apt-get update && sudo apt-get install -y cbmc && whereis goto-cc
    - uses: actions/checkout@v4
    - name: Install ESBMC
      run: wget https://github.com/esbmc/esbmc/releases/download/v7.6.1/release-ubuntu-latest.zip && unzip release-ubuntu-latest.zip
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: ESBMC=./bin/esbmc cargo test -- --ignored
